accounts.msg ={cipher}130068f3d391f0c89666e45b8350cb8680f05b2b463c0dc44fd01bb34c8daf67913d8faaae06dbb05143949efa0911cd0da94fed0d644b0265cafee4c04e60aef20993a6d886e0f4c1147e55a066faf9
accounts.build-version=2.1

accounts.mailDetails.hostName=prod-accounts@jcb.com
accounts.mailDetails.port=9010
accounts.mailDetails.from=prod-accounts@jcb.com
accounts.mailDetails.subject=Your Account Details from Eazy Bank Production Environment

accounts.activeBranches[0]=Hyderabad
accounts.activeBranches[1]=Paris
accounts.activeBranches[2]=NewYork
